### ISSUE TITLE
Pick the DB and write init.sql accordingly

### ISSUE THREAD

**Issue by seantywork** [nocode-nolunch/zoom-o#2]
expect:
  - init.sql
  - (optional) ERD maybe?

**Comment by gyuray-dev** [comment]
1. MySQL 같은 전통 RDB 쓰면서 직접 replica(slave), backup 등 설정해보고 깊게 파보기
2. MongoDB 같은 NoSQL 써보기

두 가지 방법이 있을 것 같습니다

**Comment by seantywork** [comment]
저는 일단은 지금 단계에서 
- 회원
- 비디오챗룸?
- 챗룸별 접근권한
 ...
테이블 등을 RDB 로 다루고

특정 챗룸에서 이루어졌던 텍스트챗내용을

Nosql 로 다루어 보는 것은 어떨지 생각중입니다

요거 기반으로 구체화하거나 다른 작업 중이신분은 알려주시면 감사하겠습니다
