### ISSUE TITLE
Coding convention & rule

### ISSUE THREAD

**Issue by gyuray-dev** [nocode-nolunch/zoom-o#4]
코딩 컨벤션을 정하면 좋을 것 같아요.

자바같은 경우에는 [네이버 사내 컨벤션](https://naver.github.io/hackday-conventions-java/) 같은거 그대로 적용해 쓰기도 하는데요,
자바스크립트는 이런 게 있을지 모르겠네요.

저는 일단 자바스크립트 변수 선언할 때 const, let, var를 구분해서 사용하면 좋을 것 같아요.
- **var**는 자바스크립트의 흑역사라고 쓰지 말라고 하더라구요
- **const**는 변하지 않을 immutable한 데이터를 담을 때 쓰기 때문에, 모든 참조 객체나 상수값은 const를 default로 쓰면 좋을 것 같습니다.
- **let**은 참조나 값이 변경되는 변수를 선언할 때만 사용하도록 해서 나중에 이 값이 변하겠구나~ 알 수 있도록 하는 게 좋을 것 같습니다.

그 외에
- DB 테이블, 컬럼 등 DB 관련 네이밍은 스네이크 표기법(ex> user_name)을, 나머지는 카멜 표기법(userController.js)을 쓰기
등등 고정하고 싶은 컨벤션이 있으면 댓글을 달아주세요~

**Comment by seantywork** [comment]
이거 괜찮은거 같아요

리드미에 Rules 쪽에 컨벤션 룰 넣을거 있으면 PR해주시면 좋을거 같습니다

저는 출발단계에서는 너무 복잡하지만 않으면 일단 오케이라고 생각합니다
